name: Verify Build

on:
  - push
  - pull_request:
      branches: [main]

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download

    - name: Building
      run: make build
